// Generates bridge/dcn/src/Fake/Fake.generated.cs from docs/protocol/dcn-swapi/{api,types}.json (WO-061).
// The fake mirrors the documented DCN-SW API surface (same type, member and parameter names, out parameters, events)
// so the bridge's reflection code can be tested without the Bosch DLLs. Interfaces are implemented explicitly, as an
// obfuscated assembly may do, so the bridge must reflect over interfaces, not classes.
// Usage (repo root): node bridge/dcn/tools/gen-fake.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../../../docs/protocol/dcn-swapi/', import.meta.url);
const api = JSON.parse(readFileSync(new URL('api.json', dir), 'utf8'));
const types = JSON.parse(readFileSync(new URL('types.json', dir), 'utf8'));
const out = new URL('../src/Fake/Fake.generated.cs', import.meta.url);

const SKIP = new Set(['DcnApi', 'DcnApiObject']);
/** Types still referenced without a definition (none since the DLL additions, WO-068). */
const UNDOCUMENTED = '';

const L = [];
const w = (s = '') => L.push(s);
w('// <auto-generated> by bridge/dcn/tools/gen-fake.mjs from docs/protocol/dcn-swapi. Do not edit. </auto-generated>');
w('#pragma warning disable CS0067, CS0649, CS0169');
w('using System;');
w('using System.Collections.Generic;');
w('');
w('namespace DcnBridge.Fake');
w('{');
w(UNDOCUMENTED.trimEnd());

for (const [name, t] of Object.entries(types)) {
  if (SKIP.has(name)) continue;
  if (t.kind === 'enum') {
    w(`  public enum ${name} { ${t.values.map(v => `${v.name} = ${v.value}`).join(', ')} }`);
  } else if (t.kind === 'delegate') {
    const m = /delegate\s+void\s+(\w+)\s*\(\s*Object\s+\w+,\s*(\w+)\s+\w+\s*\)/.exec(t.csharp);
    w(`  public delegate void ${name}(object sender, ${m[2]} e);`);
  } else {
    const base = (t.inherits ?? []).filter(b => b !== 'IDisposable');
    w(`  public ${t.kind === 'struct' ? 'struct' : 'class'} ${name}${base.length ? ` : ${base.join(', ')}` : ''}`);
    w('  {');
    for (const f of t.fields ?? []) {
      if (f.constant) w(`    public const ${f.type} ${f.name} = ${f.value ?? 0};`); // real values from the DLLs (WO-068)
      else w(`    public ${f.type} ${f.name};`);
    }
    for (const p of t.properties ?? []) w(`    public ${p.type} ${p.name} { get; set; }`);
    w('  }');
  }
}

const params = m => m.params.map(p => `${p.direction === 'out' ? 'out ' : p.direction === 'ref' ? 'ref ' : ''}${p.type} ${p.name}`).join(', ');
const handlerType = e => e.handler || 'EventHandler';

// Sub-interfaces + explicit implementations
const ifaces = Object.entries(api.interfaces);
for (const [key, i] of ifaces) {
  w(`  public interface ${i.interface}`);
  w('  {');
  for (const m of i.methods) w(`    API_ERROR ${m.name}(${params(m)});`);
  for (const p of i.properties) w(`    ${p.type} ${p.name} { get; }`);
  for (const e of i.events) w(`    event ${handlerType(e)} ${e.name};`);
  w('  }');
  w(`  public sealed class Fake${i.interface} : ${i.interface}, IFakeRaise`);
  w('  {');
  for (const m of i.methods) {
    w(`    API_ERROR ${i.interface}.${m.name}(${params(m)})`);
    w('    {');
    w(`      var a = new object[] { ${m.params.map(p => (p.direction === 'out' ? 'null' : p.name)).join(', ')} };`);
    w(`      var r = FakeBehavior.Call(this, "${key}", "${m.name}", a);`);
    m.params.forEach((p, idx) => { if (p.direction !== 'in') w(`      ${p.name} = (${p.type})FakeBehavior.Out(a[${idx}], typeof(${p.type}));`); });
    w('      return r;');
    w('    }');
  }
  for (const p of i.properties) w(`    ${p.type} ${i.interface}.${p.name} => FakeBehavior.Allowed("${key}.${p.name}");`);
  for (const e of i.events) {
    w(`    private ${handlerType(e)} _${e.name};`);
    w(`    event ${handlerType(e)} ${i.interface}.${e.name} { add { _${e.name} += value; } remove { _${e.name} -= value; } }`);
  }
  w('    public void Raise(string name, object args)');
  w('    {');
  w('      switch (name)');
  w('      {');
  for (const e of i.events) w(`        case "${e.name}": _${e.name}?.Invoke(this, (${e.args === 'EventArgs' ? 'EventArgs' : e.args})args); break;`);
  w('        default: throw new ArgumentException("no event " + name);');
  w('      }');
  w('    }');
  w('  }');
}

// Roots
for (const [group, root] of Object.entries(api.entry.roots)) {
  const subs = root.members.properties.filter(p => ifaces.some(([, i]) => i.interface === p.type));
  const flags = root.members.properties.filter(p => p.type === 'bool' && p.name !== 'IsAvailable');
  w(`  public interface ${root.interface} : IDisposable`);
  w('  {');
  w('    API_ERROR Initialize(string connectionString, string userName, string password);');
  w('    API_ERROR Terminate();');
  w('    bool IsAvailable { get; }');
  for (const f of flags) w(`    bool ${f.name} { get; }`);
  for (const s of subs) w(`    ${s.type} ${s.name} { get; }`);
  w('    event EventHandler AvailabilityChange;');
  w('    event EventHandler AuthorizationChange;');
  w('  }');
  w(`  public sealed class Fake${root.interface} : ${root.interface}, IFakeRoot`);
  w('  {');
  for (const s of subs) w(`    private readonly Fake${s.type} _${s.name} = new Fake${s.type}();`);
  w(`    public string Group => "${group}";`);
  w('    public bool Available { get; set; }');
  w(`    API_ERROR ${root.interface}.Initialize(string connectionString, string userName, string password) => FakeBehavior.Initialize(this, connectionString, userName, password);`);
  w(`    API_ERROR ${root.interface}.Terminate() => FakeBehavior.Terminate(this);`);
  w(`    bool ${root.interface}.IsAvailable => Available;`);
  for (const f of flags) w(`    bool ${root.interface}.${f.name} => Available && FakeBehavior.Allowed("${group}.${f.name}");`);
  for (const s of subs) w(`    ${s.type} ${root.interface}.${s.name} => _${s.name};`);
  w('    private EventHandler _AvailabilityChange, _AuthorizationChange;');
  w(`    event EventHandler ${root.interface}.AvailabilityChange { add { _AvailabilityChange += value; } remove { _AvailabilityChange -= value; } }`);
  w(`    event EventHandler ${root.interface}.AuthorizationChange { add { _AuthorizationChange += value; } remove { _AuthorizationChange -= value; } }`);
  w('    public void RaiseAvailability() { _AvailabilityChange?.Invoke(this, EventArgs.Empty); _AuthorizationChange?.Invoke(this, EventArgs.Empty); }');
  w('    public void Dispose() { }');
  w('  }');
}
w('  /// <summary>Stand-in for Bosch.Dcn.Ecpc.Client.Api.Logic.DcnApi.</summary>');
w('  public static class FakeDcnApi');
w('  {');
for (const root of Object.values(api.entry.roots)) w(`    public static ${root.interface} ${root.property.split('.')[1]} { get; } = new Fake${root.interface}();`);
w('  }');
w('}');

writeFileSync(out, `${L.join('\n')}\n`);
console.log(`wrote ${out.pathname} (${L.length} lines)`);
