// Generates bridge/dicentis/src/Fake/Fake.generated.cs from docs/protocol/dcnm-api/{api,types}.json (WO-078).
// The fake mirrors the documented DCNM API surface (type, member and parameter names, Task<T> + onFinish signatures,
// ApiEventArgs<T> events, properties, data classes with only their documented constructors) so the bridge's reflection
// code can be tested without the Bosch DLLs. Interfaces are implemented explicitly, so the bridge must reflect over the
// interfaces. Discovery cases the real DLL may have are reproduced on purpose:
// - IControlCamera, IPrepareCamera, ISystemVideoControl: extra (undocumented) WindowsApiInstance properties;
// - IRoomAudioControl: implemented by the SystemAudioControlApi object; IPrepareParticipant: by PrepareParticipant2.
// Behaviour lives in src/Fake/FakeBehavior.cs. Usage (repo root): node bridge/dicentis/tools/gen-fake.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../../../docs/protocol/dcnm-api/', import.meta.url);
const api = JSON.parse(readFileSync(new URL('api.json', dir), 'utf8'));
const types = JSON.parse(readFileSync(new URL('types.json', dir), 'utf8'));
const out = new URL('../src/Fake/Fake.generated.cs', import.meta.url);

const EXTRA_PROPERTIES = { ControlCamera: 'IControlCamera', PrepareCamera: 'IPrepareCamera', SystemVideoControl: 'ISystemVideoControl' };
const EXTRA_IMPLEMENTS = { ISystemAudioControl: ['IRoomAudioControl'], IPrepareParticipant2: ['IPrepareParticipant'] };
const SKIP_BASES = new Set(['IEquatable<EventKey>']);

const interfaces = { ...api.interfaces, ...api.otherInterfaces };
const byName = Object.fromEntries(Object.values(interfaces).map(i => [i.interface, i]));
const L = [];
const w = (s = '') => L.push(s);
const cls = name => name.replace(/<T>$/, '');

w('// <auto-generated> by bridge/dicentis/tools/gen-fake.mjs from docs/protocol/dcnm-api. Do not edit. </auto-generated>');
w('#pragma warning disable CS0067, CS0649, CS0169, CS0618, CS0108, CS0114');
w('using System;');
w('using System.Collections.Generic;');
w('using System.Collections.ObjectModel;');
w('using System.Threading;');
w('using System.Threading.Tasks;');
w('');
w('namespace DicentisBridge.Fake');
w('{');

// ---------------------------------------------------------------- enums, delegates
for (const [name, e] of Object.entries(types.enums)) {
  w(`  ${e.flags ? '[Flags] ' : ''}public enum ${name} { ${e.members.map(m => `${m.name} = ${m.value}`).join(', ')} }`);
}
for (const [name, d] of Object.entries(types.delegates)) {
  w(`  public delegate ${d.returns} ${name}(${d.params.map(p => `${p.type} ${p.name}`).join(', ')});`);
}

// ---------------------------------------------------------------- data classes
for (const [name, c] of Object.entries(types.classes)) {
  const base = c.base.filter(b => !SKIP_BASES.has(b));
  const decl = name === 'ApiEventArgs<T>' ? 'ApiEventArgs<T>' : name;
  const self = cls(name);
  w(`  public ${c.kind === 'struct' ? 'struct' : 'class'} ${decl}${base.length ? ` : ${base.join(', ')}` : ''}`);
  w('  {');
  const isException = base.includes('Exception');
  if (isException) {
    w(`    public ${self}() { }`);
    w(`    public ${self}(string message) : base(message) { }`);
  } else if (c.kind !== 'struct') {
    // A documented parameterless constructor is public; otherwise a protected one lets derived fakes chain to it while
    // the bridge (public constructors only) cannot use it.
    w(`    ${c.constructors.some(k => !k.params.length) ? 'public' : 'protected'} ${self}() { }`);
    const props = new Map(c.properties.map(p => [p.name.toLowerCase(), p]));
    for (const ctor of c.constructors) {
      if (!ctor.params.length) continue;
      const params = ctor.params.map(p => `${p.type} ${p.name}${p.default !== undefined ? ` = ${p.default}` : ''}`).join(', ');
      // Assign only when the types match: the real classes convert some arguments (IEnumerable → IList, enum → bool).
      const assigns = ctor.params.filter(p => props.get(p.name.toLowerCase())?.type === p.type && props.get(p.name.toLowerCase()).name !== self)
        .map(p => `${props.get(p.name.toLowerCase()).name} = ${p.name};`).join(' ');
      w(`    public ${self}(${params}) { ${assigns} }`);
    }
  }
  for (const p of c.properties) {
    if (p.name === self) continue; // a member cannot have the class's name (CS0542)
    w(`    public ${p.type} ${p.name} { get; ${p.access === 'get' ? 'private set; ' : 'set; '}}`);
  }
  for (const f of c.fields ?? []) {
    if (/^public (const|static readonly) /.test(f.cs)) w(`    ${f.cs};`);
  }
  w('  }');
}

// ---------------------------------------------------------------- interfaces
const sig = (m, withDefaults) => {
  const ps = m.params.map(p => `${p.modifier && p.modifier !== 'in' ? `${p.modifier} ` : ''}${p.type} ${p.name}${withDefaults && p.default !== undefined ? ` = ${p.default}` : ''}`);
  if (m.callback) ps.push(`Action<${m.returns.type}> onFinish${withDefaults ? ' = null' : ''}`);
  return ps.join(', ');
};
for (const i of Object.values(interfaces)) {
  const bases = [...i.inherits, ...(i.interface === 'ICapabilities' ? [] : ['IDisposable'])];
  w(`  public interface ${i.interface}${bases.length ? ` : ${bases.join(', ')}` : ''}`);
  w('  {');
  for (const m of i.methods) w(`    ${m.returns.type} ${m.name}(${sig(m, true)});`);
  for (const e of i.events) w(`    event ${e.handler} ${e.name};`);
  for (const p of i.properties) w(`    ${p.type} ${p.name} { ${p.access === 'get; set' ? 'get; set;' : p.access === 'set' ? 'set;' : 'get;'} }`);
  w('  }');
}

// ---------------------------------------------------------------- implementations
const closure = name => {
  const seen = [];
  const walk = n => { if (seen.includes(n) || !byName[n]) return; seen.push(n); for (const b of byName[n].inherits) walk(b); };
  walk(name);
  for (const extra of EXTRA_IMPLEMENTS[name] ?? []) walk(extra);
  return seen;
};
const args = m => m.params.map(p => p.name).join(', ');
for (const i of Object.values(interfaces)) {
  const all = closure(i.interface);
  const implemented = [i.interface, ...(EXTRA_IMPLEMENTS[i.interface] ?? [])];
  w(`  public sealed class Fake${i.interface} : FakeObject, ${implemented.join(', ')}${i.interface === 'ICapabilities' ? '' : ', IDisposable'}`);
  w('  {');
  w(`    public Fake${i.interface}() : base("${i.interface}") { }`);
  if (i.interface !== 'ICapabilities') w('    void IDisposable.Dispose() { }');
  for (const n of all) {
    const t = byName[n];
    for (const m of t.methods) {
      const ret = m.returns.type;
      const a = `"${n}", "${m.name}"`;
      const rest = args(m) ? `, ${args(m)}` : '';
      let body;
      if (ret === 'Task') body = `Done0(${a}, ${m.callback ? 'onFinish' : 'null'}${rest})`;
      else if (ret.startsWith('Task<')) body = `Done<${ret.slice(5, -1)}>(${a}, ${m.callback ? 'onFinish' : 'null'}${rest})`;
      else if (ret === 'void') body = `Sync<object>(${a}${rest})`;
      else body = `Sync<${ret}>(${a}${rest})`;
      w(`    ${ret} ${n}.${m.name}(${sig(m, false)})${ret === 'void' ? ` { ${body}; }` : ` => ${body};`}`);
    }
    for (const e of t.events) w(`    event ${e.handler} ${n}.${e.name} { add { On("${n}", "${e.name}", value); } remove { Off("${n}", "${e.name}", value); } }`);
    for (const p of t.properties) {
      const get = `get => Get<${p.type}>("${n}", "${p.name}");`;
      const set = `set => Set("${n}", "${p.name}", value);`;
      w(`    ${p.type} ${n}.${p.name} { ${p.access === 'set' ? set : p.access === 'get; set' ? `${get} ${set}` : get} }`);
    }
  }
  w('  }');
}

// ---------------------------------------------------------------- entry
w('  /// <summary>Fake of Bosch.Dcnm.Interfaces.Api.WindowsApiInstance: one object per interface, created in the constructor.</summary>');
w('  public sealed class WindowsApiInstance : IDisposable');
w('  {');
const entryProps = [...api.entry.properties.map(p => [p.name, p.type]), ...Object.entries(EXTRA_PROPERTIES)];
w('    public WindowsApiInstance()');
w('    {');
for (const [name, type] of entryProps) w(`      ${name} = FakeBehavior.Register(new Fake${type}());`);
w('      FakeBehavior.Wire();');
w('    }');
for (const [name, type] of entryProps) w(`    public ${type} ${name} { get; private set; }`);
w('    public void Shutdown() => FakeBehavior.Shutdown();');
w('    public void Dispose() { }');
w('  }');
w('}');

writeFileSync(out, L.join('\n') + '\n');
console.log(`wrote ${out.pathname} (${L.length} lines)`);
